#!/usr/bin/env bash

XT_MAIL_DISABLE=${XT_MAIL_DISABLE:-0}
XT_MAIL_SERVER=${XT_MAIL_SERVER:-smtp}
XT_MAIL_ROOT_TO=${XT_MAIL_ROOT_TO:-postman}
XT_MAIL_HOSTNAME=${XT_MAIL_HOSTNAME:-$(hostname)}

if [ $XT_MAIL_DISABLE -ne 0 ]; then
  echo "email system disabled by XT_MAIL_DISABLE env variable"
  exit 0
fi

chfn -f "root at $XT_MAIL_HOSTNAME" root

cat <<EOF > /etc/ssmtp/ssmtp.conf
root=root
mailhub=$XT_MAIL_SERVER
EOF

#cat <<EOF > /etc/ssmtp/revaliases
#root:$XT_MAIL_ROOT_TO:$XT_MAIL_SERVER
#EOF
