#!/usr/bin/env bash

if [ -z "$ETCD_NODE" ]
then
  echo "Missing ETCD_NODE env var"
  exit -1
fi

echo "lb instance using etcd node: $ETCD_NODE"

## make sure all needed keys are created
curl -sS -L -X PUT -d dir=true http://$ETCD_NODE/v2/keys/lb/backends
curl -sS -L -X PUT -d dir=true http://$ETCD_NODE/v2/keys/lb/domains

## create /etc/haproxy/custom.cfg if not mapped
if [ ! -f /etc/haproxy/custom.cfg ]; then
  touch /etc/haproxy/custom.cfg
fi
