FROM bigm/base-deb

# don't be ascetic
RUN /xt/tools/_apt_install rsync wget tar bzip2 zip p7zip unzip mc less tmux nano vim telnet curl inetutils-ping procps psmisc
RUN echo "SELECTED_EDITOR=/usr/bin/vim.basic" > /root/.selected_editor