#!/usr/bin/env bash

set -e

FOLDER=/etc/nagios3
USER=nagios

if [ ! -d "$FOLDER" ]; then
  echo "you have to mount '$FOLDER' folder to Docker host"
  exit 1
fi

if [ ! -f "$FOLDER/nagios.cfg" ]; then
  echo "populate '$FOLDER' with original content"
  cp -a "$FOLDER"_orig/. "$FOLDER"
  chown -R $USER "$FOLDER"
fi

exit 0
