#!/usr/bin/env bash

# fix permissions on the log dir
mkdir -p /var/log/squid3
chmod -R 755 /var/log/squid3
chown -R proxy:proxy /var/log/squid3

# fix permissions on the cache dir
mkdir -p /var/spool/squid3
chown -R proxy:proxy /var/spool/squid3

# initialize the cache_dir
/usr/sbin/squid3 -N -f /etc/squid3/squid.conf -z
