#!/usr/bin/env bash

### create link to production/development php.ini version
PHP_CONF_VERSION=${PHP_CONF_VERSION:-production}
if [ ! -f /usr/local/etc/php/php.ini ]; then
    ln -s /usr/local/etc/php/php.ini-${PHP_CONF_VERSION} /usr/local/etc/php/php.ini
fi

### set timezone
if [ -n "$PHP_TIMEZONE" ]; then
    cat <<EOF > /usr/local/etc/php/conf.d/_custom.ini
date.timezone = "$PHP_TIMEZONE"
apc.shm_size = 192M
short_open_tag=On
session.gc_maxlifetime=1209600

; Use igbinary as session serializer
session.serialize_handler=igbinary

; Enable or disable compacting of duplicate strings
; The default is On.
igbinary.compact_strings=On

; Use igbinary as serializer in APC cache (3.1.7 or later)
apc.serializer=igbinary
EOF
fi

# expose_php = Off
