#!/bin/bash
set -e

# Redirect stderr so everything ends up in the log file
exec 2>&1

PATH_ROOT=/prj/data/openfire
mkdir -p $PATH_ROOT
#chown -R openfire:openfire /data/openfire

# populate default openfire configuration if it does not exist
if [ ! -d $PATH_ROOT/etc ]; then
  mv /etc/openfire $PATH_ROOT/etc
fi
rm -rf /etc/openfire
ln -sf $PATH_ROOT/etc /etc/openfire

if [ ! -d $PATH_ROOT/lib ]; then
  mv /var/lib/openfire $PATH_ROOT/lib
fi
rm -rf /var/lib/openfire
if [ -d $PATH_ROOT/lib ]; then
  ln -sf $PATH_ROOT/lib /var/lib/openfire
fi

# /var/log/openfire
if [ ! -d $PATH_ROOT/log ]; then
  mv /var/log/openfire $PATH_ROOT/log
fi
rm -rf /var/log/openfire
if [ -d $PATH_ROOT/lib ]; then
  ln -sf $PATH_ROOT/log /var/log/openfire
fi

# restore
if [ -d $PATH_ROOT/restore_this ]; then
  echo "!!! restoring data from $PATH_ROOT/restore_this"
  cp -f $PATH_ROOT/restore_this/openfire* $PATH_ROOT/lib/embedded-db/
  chown root:root $PATH_ROOT/lib/embedded-db/*
  cp -f $PATH_ROOT/restore_this/conf/* $PATH_ROOT/etc/
  chown root:root $PATH_ROOT/etc/*
  # make sure we don't restore it again
  mv $PATH_ROOT/restore_this $PATH_ROOT/restore_this_DONE
fi

echo "Starting openfire..."
exec java \
  -server \
  -Xmx$OPENFIRE_XMX \
  -DopenfireHome=/usr/share/openfire \
  -Dopenfire.lib.dir=/usr/share/openfire/lib \
  -classpath /usr/share/openfire/lib/startup.jar \
  -jar /usr/share/openfire/lib/startup.jar
