#!/bin/sh

# Redirect stderr so everything ends up in the log file
exec 2>&1

exec java \
	-XX:MaxMetaspaceSize=$YOUTRACK_MAX_METASPACE -Xmx1g \
	-Duser.home=/var/lib/youtrack \
	-Djavax.net.ssl.trustStore=$JAVA_HOME/jre/lib/security/cacerts \
	-Djavax.net.ssl.trustStorePassword=$YOUTRACK_TRUST_STORE_PASSWORD \
	-Djetbrains.youtrack.disableBrowser=true -Djetbrains.youtrack.enableGuest=false \
	-Djetbrains.mps.webr.log4jPath=/xt/youtrack/log4j.xml -Djava.awt.headless=true \
	-jar /usr/local/youtrack/youtrack.jar 8080  2>&1
