[template]
prefix = "haproxy-discover"
keys = [
  "services",
  "tcp-services"
]

owner = "root"
mode = "0644"
src = "haproxy.tmpl"
dest = "/etc/haproxy/haproxy.cfg"

check_cmd = "/usr/sbin/haproxy -c -f {{ .src }} 2> /tmp/check.out"
reload_cmd = "haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf $(cat /var/run/haproxy.pid)"
