#!/usr/bin/env bash

if [ -z "$DOWNLOAD_RSYNC" ]; then
  exit 0
fi

echo "download source code from rsync server"
if [ ! -d /data/prj ]; then
  mkdir -p /data/prj
fi
rsync -a --delete $DOWNLOAD_RSYNC /data/prj
