#!/bin/bash

if [ ! -z "$1" ]; then
    apt-get -y autoremove -yq --force-yes --purge $@
fi

apt-get autoremove -yq --force-yes
apt-get clean -yq --force-yes
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*