#!/bin/bash

if [ ! -z "$1" ]; then
    apt-get update -qq
    apt-get install -yqq --force-yes --no-install-recommends $@
    apt-get autoremove
    apt-get clean
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
fi