#!/usr/bin/env bash

proxy=172.17.42.1:3128
if nc -w 1 -z ${proxy/:/ }; then
    echo "curl proxy: $proxy"
    curl -x http://$proxy/ -sSL --retry 5 --retry-delay 5 $2 > $1
else
    curl -sSL --retry 5 --retry-delay 5 $2 > $1
fi

if [ ! -z $3 ]; then
    if [ ${#3} -eq 32 ]; then
        echo "$3 $1" | /usr/bin/md5sum -c
    else
        echo "$3 $1" | /usr/bin/sha1sum -c
    fi
fi
