#!/usr/bin/env bash

curl -sSL --retry 5 --retry-delay 5 $2 > $1

if [ ! -z $3 ]; then
    if [ ${#3} -eq 32 ]; then
        echo "$3 $1" | /usr/bin/md5sum -c
    else
        echo "$3 $1" | /usr/bin/sha1sum -c
    fi
fi
