#!/usr/bin/env bash
# if you need to use mail command from bash add to Dockerfile: RUN /xt/tools/_apt_install heirloom-mailx
#
# alternative solutions: http://untroubled.org/nullmailer/, https://www.sthu.org/code/smailq.html

/xt/tools/_apt_install ssmtp

if [ ! -d /prj/startup ]; then
  mkdir -p /prj/startup
fi
cp -a /xt/tools/startup/00ssmtp /prj/startup/00ssmtp
