#!/usr/bin/env bash

if [ "$1" = "full" ]; then
    /xt/tools/_apt_install tar bzip2 zip p7zip unzip \
      mc less tmux nano vim heirloom-mailx \
      rsync wget curl dnsutils inetutils-ping telnet \
      procps psmisc
else
    /xt/tools/_apt_install mc nano vim less procps
fi

echo "SELECTED_EDITOR=/usr/bin/vim.basic" > /root/.selected_editor
