#!/bin/bash

if [ ! -z "$1" ]; then
    apt-get update -qq
    apt-get install -yqq --no-install-recommends software-properties-common
    #
    add-apt-repository -y $1
    apt-get update -qq
    apt-get install -yqq --force-yes --no-install-recommends ${*:2}
    #
    add-apt-repository -r $1
    apt-get remove --purge -y software-properties-common python-software-properties
    apt-get autoremove
    apt-get clean
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
fi