#!/bin/bash

if [ ! -z "$1" ]; then
    if [ -f /usr/bin/add-apt-repository ]; then
        IS_PPA_ENABLED_IMAGE=1
    else
        IS_PPA_ENABLED_IMAGE=0
    fi

    if [ $IS_PPA_ENABLED_IMAGE -eq 0 ]; then
        echo "temporary installing software-properties-common"
        apt-get update -qq
        apt-get install -yq --force-yes --no-install-recommends software-properties-common
    fi
    #
    add-apt-repository -y $1
    apt-get update -qq
    apt-get install -yq --force-yes --no-install-recommends ${*:2}
    #
    add-apt-repository -r $1
    if [ $IS_PPA_ENABLED_IMAGE -eq 0 ]; then
        echo "removing temporare software-properties-common"
        apt-get remove -yq --force-yes --purge software-properties-common python-software-properties
    fi
    apt-get autoremove -yq --force-yes
    apt-get clean -yq --force-yes
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
fi